In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 

# Q3 & 4
df = pd.read_csv('Iowa_Liquor.csv', low_memory=False)
df.dropna()   #why isn't it dropping the NaN values???

df['Year'] = df['Date'].apply(lambda x: int(x.split('/')[2]))

df_2015 = df.loc[df['Year']==15]

print len(df_2015['Store Number'].unique())

def erase(symbol):
    symbol = symbol.replace('$','')
    symbol = symbol.replace(',','')
    return float(symbol)

df_2015['State Bottle Cost'] = df_2015['State Bottle Cost'].apply(lambda x: erase(x))
df_2015['State Bottle Retail'] = df_2015['State Bottle Retail'].apply(lambda x: erase(x))
df_2015['Sale (Dollars)'] = df_2015['Sale (Dollars)'].apply(lambda x: erase(x))

#Make a pivot table for sales in 2015 by store number

ts2015 = pd.pivot_table(df_2015, index = 'Store Number', values = ['Sale (Dollars)'], aggfunc = np.sum)
print ts2015

#this gives the total sales for each store in 2015

df_2015['At Cost'] = df_2015['State Bottle Cost'] * df_2015['Bottles Sold']

print df_2015.head()

df_2015['Store Profit'] = df_2015['Sale (Dollars)'] - df_2015['At Cost']

print df_2015['Store Profit']

profit2015 = pd.pivot_table(df_2015, index = 'Store Number', values = ['Store Profit'], aggfunc= np.sum)

print profit2015



#5 To make larger categories and a new column for those categories
def categorize(item):   
    try: 
        if 'VODKA' in item:
            item = 'VODKA'
        elif 'RUM' in item:
            item = 'RUM'
        elif 'GIN' in item:
            item = 'GIN'
        elif 'TEQUILA' in item:
            item = 'TEQUILA'
        elif 'SCHNAPPS' in item:
            item = 'SCHNAPPS'
        elif 'WHISK' in item or 'SCOTCH' in item or 'BOURBON' in item:
            item = 'WHISKY'
        elif 'BRAND' in item:
            item = 'BRANDY'
        else:
            item = 'OTHER'
        return item 
    except:
        pass

df['Liquor Types'] = df['Category Name'].apply(categorize)
df.head()

#to see the number of total liquors in each liquor type
df['Liquor Types'].value_counts()

#to see the number of different liquors in each liquor type
#WHISKY:
df.loc[df['Liquor Types'] == 'WHISKY', 'Category Name'].unique()
df.loc[df['Liquor Types'] == 'WHISKY', 'Category Name'].value_counts()
#VODKA
df.loc[df['Liquor Types'] == 'VODKA', 'Category Name'].unique()
df.loc[df['Liquor Types'] == 'VODKA', 'Category Name'].value_counts()
#GIN
df.loc[df['Liquor Types'] == 'GIN', 'Category Name'].unique()
df.loc[df['Liquor Types'] == 'GIN', 'Category Name'].value_counts()
#RUM
df.loc[df['Liquor Types'] == 'RUM', 'Category Name'].unique()
df.loc[df['Liquor Types'] == 'RUM', 'Category Name'].value_counts()
#TEQUILA
df.loc[df['Liquor Types'] == 'TEQUILA', 'Category Name'].unique()
df.loc[df['Liquor Types'] == 'TEQUILA', 'Category Name'].value_counts()
#BRANDY
df.loc[df['Liquor Types'] == 'BRANDY', 'Category Name'].unique()
df.loc[df['Liquor Types'] == 'BRANDY', 'Category Name'].value_counts()
#SCHNAPPS
df.loc[df['Liquor Types'] == 'SCHNAPPS', 'Category Name'].unique()
df.loc[df['Liquor Types'] == 'SCHNAPPS', 'Category Name'].value_counts()
#OTHER
df.loc[df['Liquor Types'] == 'OTHER', 'Category Name'].unique()
df.loc[df['Liquor Types'] == 'OTHER', 'Category Name'].value_counts()


#to find the number of bottle sold for each broad category... another pivot table..

Bottles_Sold_Per_Category = pd.pivot_table(df, index= 'Liquor Types', values= ['Bottles Sold'], aggfunc= np.sum)
print Bottles_Sold_Per_Category

df.head()
#to find the profit for each broad category - have to drop $ from the rest of the dataframe (only dropped from 2015 before)

def erase(symbol):
    symbol = symbol.replace('$','')
    symbol = symbol.replace(',','')
    return float(symbol)

df['State Bottle Cost'] = df['State Bottle Cost'].apply(lambda x: erase(x))
df['State Bottle Retail'] = df['State Bottle Retail'].apply(lambda x: erase(x))
df['Sale (Dollars)'] = df['Sale (Dollars)'].apply(lambda x: erase(x))

#double checking
df.head()

#Creating a profits per bottle column
df['Profit Per Bottle'] = df['State Bottle Retail'] - df['State Bottle Cost']

#Total profits column
df['Total Profit'] = df['Profit Per Bottle'] * df['Bottles Sold']
#Whisky had the most bottles sold 


#Pivot table for profits for each category

Profits_By_Category = pd.pivot_table(df, index= 'Liquor Types', values= ['Total Profit'], aggfunc= np.sum)
print Profits_By_Category
#I want to limit the number of places after the decimal too, but I'm not sure how to do that.
#Whisky was the most profitable



#6 Pivot table with Broad Category, liquors in each category, max, min, volume price per bottle:

table = pd.pivot_table(df, index=['Liquor Types','Category Name'], values=['State Bottle Retail','Volume Sold (Liters)'], 
                       aggfunc=[np.max, np.min, np.sum, np.mean])
print table



#7 County by county differences
#Different counties:

df['County'].value_counts()

by_county1 = df.groupby(['County', 'Liquor Types'])['Liquor Types'].count()
by_county1

by_county2 = pd.pivot_table(df, index=['County', 'Liquor Types'], values=['Volume Sold (Liters)'], aggfunc=np.sum)
by_county2
#wasn't sure whether to use a pivot table or a groupby... couldn't figure out how to sort the values to rank them



#8

#Populations by County....

len(df['County'].value_counts())

# 5 smallest counties: Adams, Ringgold, Audubon, Taylor, Wayne
# 5 largest counties: Polk, Linn, Scott, Black Hawk, Johnson

def size(county):
    if 'Polk' in county: 
        county = 'HighPop'
    elif 'Linn' in county:
        county = 'HighPop'
    elif 'Scott' in county: 
        county = 'HighPop'
    elif 'Black Hawk' in county: 
        county = 'HighPop'
    elif 'Johnson' in county:
        county = 'HighPop'
    elif 'Adams' in county: 
        county = 'LowPop'
    elif 'Ringgold' in county:
        county = 'LowPop'
    elif 'Audubon' in county:
        county = 'LowPop'
    elif 'Taylor' in county: 
        county = 'LowPop'
    elif 'Wayne' in county:
        county = "LowPop"
    else:
        pass

High_Pop = df.loc[(df['County Name'] == 'HighPop')]
Low_Pop = df.loc[(df['County Name'] == 'LowPop')]

#I ran out of time and this is as far as I got with this one. Will continue to think on how to proceed. 
#I could probably do a groupby with the county size and store number, then find the amount of unique store numbers per county. Compare totals. I could do the same with # of bottles purchased. 



#9
# Plotting

#again, I ran out of time, but I would choose number 4 to plot. I'd make a stacked bar chart. On the x-axis I'd have different stores on the on the y axis I'd have $. 
# One segment of the stacked bars would show the total sales for the store in 2015 (would ultimately be the upper segment of the bar). The lower segment of the bar would indicate the stores profit in 2015.

1301

/Users/heatherrobbins/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/heatherrobbins/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/heatherrobbins/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/heatherrobbins/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/heatherrobbins/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

              Sale (Dollars)
Store Number
2106               321948.06
2113                19921.74
2130               250368.61
2152                13249.23
2178                75434.95
2190               319481.46
2191               283797.99
2200                57566.83
2205                57692.55
2228                49188.84
2233                59053.61
2238                 2143.26
2248               193848.20
2285               206685.19
2290               134327.89
2327                29004.37
2353                90386.47
2413               187850.84
2445                18521.98
2448                45571.22
2459                23164.13
2460                74109.94
2465                61833.11
2475                29848.55
2478                40686.10
2487                17289.61
2498                 7081.61
2500               296847.67
2501               372336.22
2502               381775.51
...                      ...
5181                 5725.62
5182                 2918.36
5183                 8169.67
5185                12463.70
5186                 4323.40
5187                18495.62
5188                14610.32
5189                13794.18
5190                 8678.36
5191                 4141.35
5192                 2774.64
5193                 2600.64
5196                 8890.73
5198                36276.74
5199                15195.32
5201                 2791.80
5203                 9959.70
5204                10138.49
5205                 1656.03
5206                 6905.69
5207                30359.21
5212                 5723.57
5213                  679.98
5215                 3169.50
9001                57101.76
9002                94582.26
9010                 1448.64
9013                18504.90
9018                21825.00
9023                  633.36

[1301 rows x 1 columns]
            Date  Store Number             City Zip Code  County Number  \
525069  12/31/15          3400       DES MOINES    50317           77.0
525070  12/31/15          4165           ANKENY    50023           77.0
525071  12/31/15          4617       DES MOINES    50317           77.0
525072  12/31/15          5089  MISSOURI VALLEY    51555           43.0
525073  12/31/15          4695          ALTOONA    50009           77.0

          County   Category     Category Name  Vendor Number  Item Number  \
525069      Polk  1051140.0    PEACH BRANDIES            115        56195
525070      Polk  1031080.0    VODKA 80 PROOF            380        37348
525071      Polk  1031080.0    VODKA 80 PROOF            380        37348
525072  Harrison  1011100.0  BLENDED WHISKIES            260        27554
525073      Polk  1081600.0   WHISKEY LIQUEUR            421        64866

                             Item Description  Bottle Volume (ml)  \
525069  Paul Masson Peach Grande Amber Brandy                 375
525070                         Phillips Vodka                1750
525071                         Phillips Vodka                1750
525072        Seagrams Seven Crown Dark Honey                 750
525073              Fireball Cinnamon Whiskey                 750

        State Bottle Cost  State Bottle Retail  Bottles Sold  Sale (Dollars)  \
525069               3.22                 4.83            24          115.92
525070               7.60                11.40             6           68.40
525071               7.60                11.40             6           68.40
525072               7.00                10.50             2           21.00
525073               8.98                13.47            12          161.64

        Volume Sold (Liters)  Volume Sold (Gallons)  Year  At Cost
525069                   9.0                   2.38    15    77.28
525070                  10.5                   2.77    15    45.60
525071                  10.5                   2.77    15    45.60
525072                   1.5                   0.40    15    14.00
525073                   9.0                   2.38    15   107.76
525069       38.64
525070       22.80
525071       22.80
525072        7.00
525073       53.88
525074       53.88
525075       21.00
525076      755.40
525077       69.00
525078       34.50
525079       12.63
525080       14.76
525081       44.28
525082       19.98
525083        9.00
525084       49.56
525085       15.72
525086       13.32
525087     2076.72
525088        9.60
525089       11.00
525090        7.76
525091        6.00
525092       11.00
525093       20.48
525094       13.50
525095       10.50
525096       21.54
525097       21.54
525098        6.50
            ...
1048545      63.00
1048546       9.00
1048547      15.72
1048548       3.92
1048549       5.01
1048550      53.76
1048551      21.60
1048552       4.98
1048553      12.39
1048554      96.00
1048555      10.00
1048556      10.92
1048557       2.45
1048558       8.50
1048559       6.64
1048560      62.76
1048561      46.80
1048562       4.30
1048563      36.00
1048564       4.50
1048565      14.19
1048566      36.96
1048567      90.00
1048568       8.60
1048569      10.38
1048570       8.68
1048571      24.60
1048572      29.64
1048573      27.72
1048574      45.24
Name: Store Profit, dtype: float64
              Store Profit
Store Number
2106             107433.37
2113               6683.47
2130              83533.51
2152               4450.54
2178              25321.01
2190             106676.82
2191              94673.21
2200              19339.98
2205              19285.65
2228              16533.30
2233              19744.16
2238                714.71
2248              64759.95
2285              69066.55
2290              44934.57
2327               9710.05
2353              30225.53
2413              62730.99
2445               6187.58
2448              15210.10
2459               7761.15
2460              24852.73
2465              20663.80
2475              10030.69
2478              13565.90
2487               5818.53
2498               2375.30
2500              99427.98
2501             124624.87
2502             127946.95
...                    ...
5181               1909.25
5182                973.52
5183               2732.27
5185               4160.17
5186               1445.87
5187               6171.82
5188               4874.98
5189               4614.60
5190               2900.49
5191               1381.29
5192                925.14
5193                870.06
5196               2965.22
5198              12102.57
5199               5120.76
5201                930.93
5203               3335.41
5204               3381.81
5205                557.27
5206               2320.49
5207              10125.55
5212               1913.03
5213                226.80
5215               1061.65
9001              19036.74
9002              31542.46
9010                483.00
9013               6174.21
9018               7275.00
9023                211.20

[1301 rows x 1 columns]

In [134]:
df['Total Profit'] = df['Profit Per Bottle'] * df['Bottles Sold']

In [135]:
df.head()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,...,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),Year,Liquor Types,Profit,Profit Per Bottle,Total Profit
0,3/31/16,5029,DAVENPORT,52806,82.0,Scott,1022100.0,TEQUILA,370,87152,...,14.99,12,179.88,4.5,1.19,16,TEQUILA,5.00,5.00,60.00
1,3/31/16,5029,DAVENPORT,52806,82.0,Scott,1022100.0,TEQUILA,395,89197,...,18.75,2,37.50,2.0,0.53,16,TEQUILA,6.25,6.25,12.50
2,3/31/16,4959,CEDAR FALLS,50613,7.0,Black Hawk,1071100.0,AMERICAN COCKTAILS,380,63959,...,8.96,6,53.76,10.5,2.77,16,OTHER,2.99,2.99,17.94
3,3/31/16,2190,DES MOINES,50314,77.0,Polk,1031200.0,VODKA FLAVORED,205,40597,...,3.36,48,161.28,9.6,2.54,16,VODKA,1.12,1.12,53.76
4,3/31/16,5240,WEST BRANCH,52358,NaN,NaN,1081200.0,CREAM LIQUEURS,305,73055,...,18.75,6,112.50,4.5,1.19,16,OTHER,6.25,6.25,37.50

In [136]:
Profits_By_Category = pd.pivot_table(df, index= 'Liquor Types', values= ['Total Profit'], aggfunc= np.sum)
print Profits_By_Category
#I want to limit the number of places after the decimal too, but I'm not sure how to do that.

              Total Profit
Liquor Types
BRANDY        1.940859e+06
GIN           1.101055e+06
OTHER         4.900287e+06
RUM           5.631510e+06
SCHNAPPS      1.726182e+06
TEQUILA       2.376625e+06
VODKA         1.042142e+07
WHISKY        1.726097e+07

In [138]:
df.head()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,...,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),Year,Liquor Types,Profit,Profit Per Bottle,Total Profit
0,3/31/16,5029,DAVENPORT,52806,82.0,Scott,1022100.0,TEQUILA,370,87152,...,14.99,12,179.88,4.5,1.19,16,TEQUILA,5.00,5.00,60.00
1,3/31/16,5029,DAVENPORT,52806,82.0,Scott,1022100.0,TEQUILA,395,89197,...,18.75,2,37.50,2.0,0.53,16,TEQUILA,6.25,6.25,12.50
2,3/31/16,4959,CEDAR FALLS,50613,7.0,Black Hawk,1071100.0,AMERICAN COCKTAILS,380,63959,...,8.96,6,53.76,10.5,2.77,16,OTHER,2.99,2.99,17.94
3,3/31/16,2190,DES MOINES,50314,77.0,Polk,1031200.0,VODKA FLAVORED,205,40597,...,3.36,48,161.28,9.6,2.54,16,VODKA,1.12,1.12,53.76
4,3/31/16,5240,WEST BRANCH,52358,NaN,NaN,1081200.0,CREAM LIQUEURS,305,73055,...,18.75,6,112.50,4.5,1.19,16,OTHER,6.25,6.25,37.50

In [154]:
table = pd.pivot_table(df, index=['Liquor Types','Category Name'], values=['State Bottle Retail','Volume Sold (Liters)'], 
                       aggfunc=[np.max, np.min, np.sum, np.mean])
table

                                                               amax  \
                                                State Bottle Retail
Liquor Types Category Name
BRANDY       AMERICAN GRAPE BRANDIES                          28.13
             APRICOT BRANDIES                                 16.94
             BLACKBERRY BRANDIES                              16.94
             CHERRY BRANDIES                                   9.75
             IMPORTED GRAPE BRANDIES                         629.99
             MISCELLANEOUS  BRANDIES                          49.89
             PEACH BRANDIES                                   10.68
GIN          AMERICAN DRY GINS                                54.00
             AMERICAN SLOE GINS                               26.25
             FLAVORED GINS                                    23.78
             IMPORTED DRY GINS                                39.75
OTHER        AMARETTO - IMPORTED                              46.70
             AMERICAN ALCOHOL                                 35.01
             AMERICAN AMARETTO                                12.11
             AMERICAN COCKTAILS                               18.74
             ANISETTE                                          7.88
             COFFEE LIQUEURS                                  37.49
             CREAM LIQUEURS                                  148.50
             CREME DE ALMOND                                  11.81
             DARK CREME DE CACAO                               8.49
             DECANTERS & SPECIALTY PACKAGES                  195.00
             DISTILLED SPIRITS SPECIALTY                      38.76
             GREEN CREME DE MENTHE                             8.66
             HIGH PROOF BEER - AMERICAN                      142.76
             IMPORTED AMARETTO                                28.49
             MISC. AMERICAN CORDIALS & LIQUEURS              103.41
             MISC. IMPORTED CORDIALS & LIQUEURS              111.33
             ROCK & RYE                                       15.75
             TRIPLE SEC                                       18.50
             WHITE CREME DE CACAO                              8.66
...                                                             ...
SCHNAPPS     IMPORTED SCHNAPPS                                23.63
             MISCELLANEOUS SCHNAPPS                           14.25
             PEACH SCHNAPPS                                   17.31
             PEPPERMINT SCHNAPPS                              18.75
             RASPBERRY SCHNAPPS                               11.81
             ROOT BEER SCHNAPPS                               13.91
             SPEARMINT SCHNAPPS                                7.50
             STRAWBERRY SCHNAPPS                               9.45
             TROPICAL FRUIT SCHNAPPS                          11.81
             WATERMELON SCHNAPPS                              11.81
TEQUILA      TEQUILA                                         280.41
VODKA        100 PROOF VODKA                                  32.99
             IMPORTED VODKA                                   63.99
             IMPORTED VODKA - MISC                            48.74
             OTHER PROOF VODKA                                27.50
             VODKA 80 PROOF                                  104.87
             VODKA FLAVORED                                   31.76
WHISKY       BLENDED WHISKIES                                 67.26
             BOTTLED IN BOND BOURBON                          48.72
             CANADIAN WHISKIES                                98.99
             CORN WHISKIES                                  9702.00
             IRISH WHISKIES                                  252.00
             JAPANESE WHISKY                                 496.23
             SCOTCH WHISKIES                                1011.24
             SINGLE BARREL BOURBON WHISKIES                 8700.00
             SINGLE MALT SCOTCH                             1090.22
             STRAIGHT BOURBON WHISKIES                       187.50
             STRAIGHT RYE WHISKIES                            60.15
             TENNESSEE WHISKIES                             9000.00
             WHISKEY LIQUEUR                                  56.09

                                                                      \
                                                Volume Sold (Liters)
Liquor Types Category Name
BRANDY       AMERICAN GRAPE BRANDIES                          480.00
             APRICOT BRANDIES                                  99.00
             BLACKBERRY BRANDIES                              168.00
             CHERRY BRANDIES                                  228.00
             IMPORTED GRAPE BRANDIES                          135.00
             MISCELLANEOUS  BRANDIES                           22.50
             PEACH BRANDIES                                    24.00
GIN          AMERICAN DRY GINS                                480.00
             AMERICAN SLOE GINS                                24.00
             FLAVORED GINS                                     27.00
             IMPORTED DRY GINS                                630.00
OTHER        AMARETTO - IMPORTED                               27.00
             AMERICAN ALCOHOL                                 126.00
             AMERICAN AMARETTO                                372.00
             AMERICAN COCKTAILS                               525.00
             ANISETTE                                          45.00
             COFFEE LIQUEURS                                  360.00
             CREAM LIQUEURS                                   810.00
             CREME DE ALMOND                                   36.00
             DARK CREME DE CACAO                               36.00
             DECANTERS & SPECIALTY PACKAGES                   945.00
             DISTILLED SPIRITS SPECIALTY                      780.00
             GREEN CREME DE MENTHE                             72.00
             HIGH PROOF BEER - AMERICAN                         0.75
             IMPORTED AMARETTO                                 72.00
             MISC. AMERICAN CORDIALS & LIQUEURS               198.00
             MISC. IMPORTED CORDIALS & LIQUEURS               540.00
             ROCK & RYE                                        13.50
             TRIPLE SEC                                       660.00
             WHITE CREME DE CACAO                             166.50
...                                                              ...
SCHNAPPS     IMPORTED SCHNAPPS                                900.00
             MISCELLANEOUS SCHNAPPS                           132.00
             PEACH SCHNAPPS                                   516.00
             PEPPERMINT SCHNAPPS                              300.00
             RASPBERRY SCHNAPPS                               117.00
             ROOT BEER SCHNAPPS                                72.00
             SPEARMINT SCHNAPPS                                24.00
             STRAWBERRY SCHNAPPS                               27.00
             TROPICAL FRUIT SCHNAPPS                           48.00
             WATERMELON SCHNAPPS                              288.00
TEQUILA      TEQUILA                                          672.00
VODKA        100 PROOF VODKA                                 1050.00
             IMPORTED VODKA                                  1575.00
             IMPORTED VODKA - MISC                            408.00
             OTHER PROOF VODKA                                 21.00
             VODKA 80 PROOF                                  2880.00
             VODKA FLAVORED                                   324.00
WHISKY       BLENDED WHISKIES                                1575.00
             BOTTLED IN BOND BOURBON                           40.50
             CANADIAN WHISKIES                               2362.50
             CORN WHISKIES                                    360.00
             IRISH WHISKIES                                  1320.00
             JAPANESE WHISKY                                   63.00
             SCOTCH WHISKIES                                  840.00
             SINGLE BARREL BOURBON WHISKIES                   180.00
             SINGLE MALT SCOTCH                               315.00
             STRAIGHT BOURBON WHISKIES                        840.00
             STRAIGHT RYE WHISKIES                            720.00
             TENNESSEE WHISKIES                              1980.00
             WHISKEY LIQUEUR                                 1440.00

                                                               amin  \
                                                State Bottle Retail
Liquor Types Category Name
BRANDY       AMERICAN GRAPE BRANDIES                           1.50
             APRICOT BRANDIES                                  2.94
             BLACKBERRY BRANDIES                               3.92
             CHERRY BRANDIES                                   5.33
             IMPORTED GRAPE BRANDIES                           1.34
             MISCELLANEOUS  BRANDIES                           2.94
             PEACH BRANDIES                                    2.94
GIN          AMERICAN DRY GINS                                 1.34
             AMERICAN SLOE GINS                                6.57
             FLAVORED GINS                                     5.09
             IMPORTED DRY GINS                                 5.88
OTHER        AMARETTO - IMPORTED                              46.70
             AMERICAN ALCOHOL                                  5.99
             AMERICAN AMARETTO                                 4.50
             AMERICAN COCKTAILS                                2.25
             ANISETTE                                          6.75
             COFFEE LIQUEURS                                   7.02
             CREAM LIQUEURS                                    6.75
             CREME DE ALMOND                                   6.75
             DARK CREME DE CACAO                               5.85
             DECANTERS & SPECIALTY PACKAGES                    5.46
             DISTILLED SPIRITS SPECIALTY                       6.77
             GREEN CREME DE MENTHE                             6.75
             HIGH PROOF BEER - AMERICAN                      142.76
             IMPORTED AMARETTO                                 8.25
             MISC. AMERICAN CORDIALS & LIQUEURS                4.50
             MISC. IMPORTED CORDIALS & LIQUEURS                5.27
             ROCK & RYE                                        7.40
             TRIPLE SEC                                        3.20
             WHITE CREME DE CACAO                              5.99
...                                                             ...
SCHNAPPS     IMPORTED SCHNAPPS                                 7.44
             MISCELLANEOUS SCHNAPPS                            1.34
             PEACH SCHNAPPS                                    4.61
             PEPPERMINT SCHNAPPS                               3.39
             RASPBERRY SCHNAPPS                                6.51
             ROOT BEER SCHNAPPS                                8.25
             SPEARMINT SCHNAPPS                                7.50
             STRAWBERRY SCHNAPPS                               7.13
             TROPICAL FRUIT SCHNAPPS                           5.50
             WATERMELON SCHNAPPS                               7.44
TEQUILA      TEQUILA                                           2.81
VODKA        100 PROOF VODKA                                   1.34
             IMPORTED VODKA                                    3.80
             IMPORTED VODKA - MISC                             4.50
             OTHER PROOF VODKA                                10.01
             VODKA 80 PROOF                                    1.34
             VODKA FLAVORED                                    3.36
WHISKY       BLENDED WHISKIES                                  1.58
             BOTTLED IN BOND BOURBON                          11.93
             CANADIAN WHISKIES                                 1.34
             CORN WHISKIES                                     5.63
             IRISH WHISKIES                                    7.65
             JAPANESE WHISKY                                  18.74
             SCOTCH WHISKIES                                   4.82
             SINGLE BARREL BOURBON WHISKIES                   21.46
             SINGLE MALT SCOTCH                                7.73
             STRAIGHT BOURBON WHISKIES                         1.58
             STRAIGHT RYE WHISKIES                            14.21
             TENNESSEE WHISKIES                                2.61
             WHISKEY LIQUEUR                                   1.34

                                                                      \
                                                Volume Sold (Liters)
Liquor Types Category Name
BRANDY       AMERICAN GRAPE BRANDIES                            0.10
             APRICOT BRANDIES                                   0.20
             BLACKBERRY BRANDIES                                0.38
             CHERRY BRANDIES                                    0.38
             IMPORTED GRAPE BRANDIES                            0.10
             MISCELLANEOUS  BRANDIES                            0.20
             PEACH BRANDIES                                     0.20
GIN          AMERICAN DRY GINS                                  0.10
             AMERICAN SLOE GINS                                 0.75
             FLAVORED GINS                                      0.75
             IMPORTED DRY GINS                                  0.38
OTHER        AMARETTO - IMPORTED                                9.00
             AMERICAN ALCOHOL                                   0.75
             AMERICAN AMARETTO                                  0.60
             AMERICAN COCKTAILS                                 0.20
             ANISETTE                                           0.75
             COFFEE LIQUEURS                                    0.38
             CREAM LIQUEURS                                     0.38
             CREME DE ALMOND                                    0.75
             DARK CREME DE CACAO                                0.75
             DECANTERS & SPECIALTY PACKAGES                     0.15
             DISTILLED SPIRITS SPECIALTY                        0.38
             GREEN CREME DE MENTHE                              0.75
             HIGH PROOF BEER - AMERICAN                         0.75
             IMPORTED AMARETTO                                  0.38
             MISC. AMERICAN CORDIALS & LIQUEURS                 0.20
             MISC. IMPORTED CORDIALS & LIQUEURS                 0.20
             ROCK & RYE                                         0.75
             TRIPLE SEC                                         0.38
             WHITE CREME DE CACAO                               0.75
...                                                              ...
SCHNAPPS     IMPORTED SCHNAPPS                                  0.38
             MISCELLANEOUS SCHNAPPS                             0.10
             PEACH SCHNAPPS                                     0.38
             PEPPERMINT SCHNAPPS                                0.38
             RASPBERRY SCHNAPPS                                 0.75
             ROOT BEER SCHNAPPS                                 0.75
             SPEARMINT SCHNAPPS                                 1.00
             STRAWBERRY SCHNAPPS                                0.75
             TROPICAL FRUIT SCHNAPPS                            0.75
             WATERMELON SCHNAPPS                                0.75
TEQUILA      TEQUILA                                            0.20
VODKA        100 PROOF VODKA                                    0.20
             IMPORTED VODKA                                     0.10
             IMPORTED VODKA - MISC                              0.20
             OTHER PROOF VODKA                                  0.75
             VODKA 80 PROOF                                     0.20
             VODKA FLAVORED                                     0.00
WHISKY       BLENDED WHISKIES                                   0.20
             BOTTLED IN BOND BOURBON                            0.75
             CANADIAN WHISKIES                                  0.10
             CORN WHISKIES                                      0.75
             IRISH WHISKIES                                     0.30
             JAPANESE WHISKY                                    0.75
             SCOTCH WHISKIES                                    0.30
             SINGLE BARREL BOURBON WHISKIES                     0.75
             SINGLE MALT SCOTCH                                 0.30
             STRAIGHT BOURBON WHISKIES                          0.10
             STRAIGHT RYE WHISKIES                              0.75
             TENNESSEE WHISKIES                                 0.10
             WHISKEY LIQUEUR                                    0.10

                                                                sum  \
                                                State Bottle Retail
Liquor Types Category Name
BRANDY       AMERICAN GRAPE BRANDIES                      212242.47
             APRICOT BRANDIES                              36077.70
             BLACKBERRY BRANDIES                           60147.51
             CHERRY BRANDIES                               10523.29
             IMPORTED GRAPE BRANDIES                      391864.38
             MISCELLANEOUS  BRANDIES                       12076.90
             PEACH BRANDIES                                21284.04
GIN          AMERICAN DRY GINS                            207907.01
             AMERICAN SLOE GINS                             4665.78
             FLAVORED GINS                                  8638.63
             IMPORTED DRY GINS                            239338.39
OTHER        AMARETTO - IMPORTED                             280.20
             AMERICAN ALCOHOL                              33358.75
             AMERICAN AMARETTO                             36090.31
             AMERICAN COCKTAILS                           254699.76
             ANISETTE                                       1154.94
             COFFEE LIQUEURS                              128247.97
             CREAM LIQUEURS                               496739.17
             CREME DE ALMOND                                1693.88
             DARK CREME DE CACAO                            5233.50
             DECANTERS & SPECIALTY PACKAGES               179267.59
             DISTILLED SPIRITS SPECIALTY                   76667.53
             GREEN CREME DE MENTHE                          8064.59
             HIGH PROOF BEER - AMERICAN                      856.56
             IMPORTED AMARETTO                             16141.33
             MISC. AMERICAN CORDIALS & LIQUEURS           129894.42
             MISC. IMPORTED CORDIALS & LIQUEURS           511829.94
             ROCK & RYE                                     4056.55
             TRIPLE SEC                                    21977.32
             WHITE CREME DE CACAO                           6037.28
...                                                             ...
SCHNAPPS     IMPORTED SCHNAPPS                            270777.77
             MISCELLANEOUS SCHNAPPS                        37014.05
             PEACH SCHNAPPS                                60326.43
             PEPPERMINT SCHNAPPS                          119674.47
             RASPBERRY SCHNAPPS                             9956.30

In [155]:
df.head()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,...,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),Year,Liquor Types,Profit,Profit Per Bottle,Total Profit
0,3/31/16,5029,DAVENPORT,52806,82.0,Scott,1022100.0,TEQUILA,370,87152,...,14.99,12,179.88,4.5,1.19,16,TEQUILA,5.00,5.00,60.00
1,3/31/16,5029,DAVENPORT,52806,82.0,Scott,1022100.0,TEQUILA,395,89197,...,18.75,2,37.50,2.0,0.53,16,TEQUILA,6.25,6.25,12.50
2,3/31/16,4959,CEDAR FALLS,50613,7.0,Black Hawk,1071100.0,AMERICAN COCKTAILS,380,63959,...,8.96,6,53.76,10.5,2.77,16,OTHER,2.99,2.99,17.94
3,3/31/16,2190,DES MOINES,50314,77.0,Polk,1031200.0,VODKA FLAVORED,205,40597,...,3.36,48,161.28,9.6,2.54,16,VODKA,1.12,1.12,53.76
4,3/31/16,5240,WEST BRANCH,52358,NaN,NaN,1081200.0,CREAM LIQUEURS,305,73055,...,18.75,6,112.50,4.5,1.19,16,OTHER,6.25,6.25,37.50

In [157]:
df['County'].unique()

array(['Scott', 'Black Hawk', 'Polk', nan, 'Cerro Gordo', 'Johnson',
       'Greene', 'Worth', 'Poweshiek', 'Crawford', 'Winnebago', 'Boone',
       'Clinton', 'Linn', 'Clarke', 'Cedar', 'Decatur', 'Warren', 'Jasper',
       'Iowa', 'Madison', 'Carroll', 'Dallas', 'Story', 'Buena Vista',
       'Woodbury', 'Appanoose', 'Wapello', 'Winneshiek', 'Fayette',
       'Marion', 'Calhoun', 'Monroe', 'Monona', 'Mahaska', 'Webster',
       'Allamakee', 'Buchanan', 'Bremer', 'Hancock', 'Kossuth', 'Sac',
       'Plymouth', 'Ida', 'Lucas', 'Davis', 'Benton', 'Clay', 'Mitchell',
       'Dubuque', 'Pottawattamie', 'Floyd', 'Hamilton', 'Sioux',
       'Marshall', 'Union', "O'Brien", 'Tama', 'Montgomery', 'Taylor',
       'Humboldt', 'Dickinson', 'Lyon', 'Jones', 'Wright', 'Cherokee',
       'Butler', 'Page', 'Emmet', 'Palo Alto', 'Adair', 'Mills',
       'Ringgold', 'Adams', 'Howard', 'Chickasaw', 'Hardin', 'Grundy',
       'Pocahontas', 'Osceola', 'Clayton', 'Jefferson', 'Muscatine',
       'Des Moines', 'Cass', 'Guthrie', 'Lee', 'Jackson', 'Washington',
       'Henry', 'Louisa', 'Delaware', 'Harrison', 'Franklin', 'Van Buren',
       'Keokuk', 'Shelby', 'Audubon', 'Wayne', 'Fremont'], dtype=object)

In [158]:
df['County'].value_counts()

Polk             191710
Linn              88765
Scott             64685
Black Hawk        59161
Johnson           50636
Story             35560
Pottawattamie     35430
Woodbury          33939
Dubuque           29281
Cerro Gordo       25032
Muscatine         15132
Des Moines        15022
Wapello           13616
Clinton           13547
Webster           12955
Marshall          11877
Lee               11808
Buena Vista       11331
Jasper            10803
Dickinson         10613
Dallas            10246
Marion             9988
Warren             9294
Bremer             8471
Poweshiek          8228
Boone              7977
Clay               7542
Carroll            7067
O'Brien            6817
Plymouth           6569
                  ...
Clarke             2445
Shelby             2405
Ida                2405
Greene             2353
Adair              2266
Franklin           2196
Grundy             2075
Pocahontas         1951
Mills              1946
Howard             1931
Chickasaw          1891
Lucas              1891
Butler             1668
Calhoun            1635
Louisa             1584
Worth              1570
Guthrie            1534
Hancock            1456
Keokuk             1417
Osceola            1370
Monroe             1345
Taylor             1241
Decatur            1090
Adams               938
Audubon             899
Van Buren           881
Ringgold            766
Davis               746
Wayne               642
Fremont             102
Name: County, dtype: int64

In [186]:
by_county1 = df.groupby(['County', 'Liquor Types'])['Liquor Types'].count()
by_county1

County      Liquor Types
Adair       BRANDY             82
            GIN                58
            OTHER             190
            RUM               275
            SCHNAPPS          149
            TEQUILA           118
            VODKA             483
            WHISKY            908
Adams       BRANDY             48
            GIN                13
            OTHER             135
            RUM                66
            SCHNAPPS           70
            TEQUILA            17
            VODKA             117
            WHISKY            472
Allamakee   BRANDY            327
            GIN               124
            OTHER             604
            RUM               465
            SCHNAPPS          393
            TEQUILA           124
            VODKA             861
            WHISKY           1382
Appanoose   BRANDY            128
            GIN                97
            OTHER             557
            RUM               448
            SCHNAPPS          331
            TEQUILA           126
                            ...
Winneshiek  OTHER             689
            RUM               576
            SCHNAPPS          457
            TEQUILA           159
            VODKA            1202
            WHISKY           1500
Woodbury    BRANDY           2066
            GIN              1054
            OTHER            4039
            RUM              4054
            SCHNAPPS         1856
            TEQUILA          1778
            VODKA            8348
            WHISKY          10594
Worth       BRANDY             78
            GIN                33
            OTHER             214
            RUM               212
            SCHNAPPS          115
            TEQUILA            57
            VODKA             360
            WHISKY            494
Wright      BRANDY             77
            GIN                63
            OTHER             264
            RUM               439
            SCHNAPPS          175
            TEQUILA           109
            VODKA             702
            WHISKY           1051
Name: Liquor Types, dtype: int64

In [187]:
by_county2 = pd.pivot_table(df, index=['County', 'Liquor Types'], values=['Volume Sold (Liters)'], aggfunc=np.sum)
by_county2
#wasn't sure whether to use a pivot table or a groupby... couldn't figure out how to sort the values to rank them

                         Volume Sold (Liters)
County     Liquor Types
Adair      BRANDY                       12.00
           GIN                          12.00
           OTHER                        48.00
           RUM                          42.00
           SCHNAPPS                     21.00
           TEQUILA                     120.00
           VODKA                        84.00
           WHISKY                      262.50
Adams      BRANDY                       10.50
           GIN                           3.50
           OTHER                        21.00
           RUM                          10.50
           SCHNAPPS                      5.25
           TEQUILA                      12.00
           VODKA                        12.00
           WHISKY                       24.00
Allamakee  BRANDY                       36.00
           GIN                          21.00
           OTHER                        31.50
           RUM                          60.00
           SCHNAPPS                     84.00
           TEQUILA                      12.00
           VODKA                       252.00
           WHISKY                      525.00
Appanoose  BRANDY                       18.00
           GIN                          31.50
           OTHER                       115.50
           RUM                         283.50
           SCHNAPPS                     21.00
           TEQUILA                      72.00
...                                       ...
Winneshiek OTHER                        85.50
           RUM                          63.00
           SCHNAPPS                     21.00
           TEQUILA                      12.00
           VODKA                       262.50
           WHISKY                     1018.50
Woodbury   BRANDY                      192.00
           GIN                         144.00
           OTHER                       768.00
           RUM                         525.00
           SCHNAPPS                    480.00
           TEQUILA                     157.50
           VODKA                       630.00
           WHISKY                     1186.50
Worth      BRANDY                       12.00
           GIN                          10.50
           OTHER                        21.00
           RUM                         315.00
           SCHNAPPS                     12.00
           TEQUILA                      21.00
           VODKA                        31.50
           WHISKY                      262.50
Wright     BRANDY                       10.50
           GIN                          12.00
           OTHER                        12.00
           RUM                          31.50
           SCHNAPPS                     12.00
           TEQUILA                      99.00
           VODKA                        63.00
           WHISKY                     1050.00

[792 rows x 1 columns]

In [190]:
len(df['County'].value_counts())

99

In [191]:
df['County'].unique()

array(['Scott', 'Black Hawk', 'Polk', nan, 'Cerro Gordo', 'Johnson',
       'Greene', 'Worth', 'Poweshiek', 'Crawford', 'Winnebago', 'Boone',
       'Clinton', 'Linn', 'Clarke', 'Cedar', 'Decatur', 'Warren', 'Jasper',
       'Iowa', 'Madison', 'Carroll', 'Dallas', 'Story', 'Buena Vista',
       'Woodbury', 'Appanoose', 'Wapello', 'Winneshiek', 'Fayette',
       'Marion', 'Calhoun', 'Monroe', 'Monona', 'Mahaska', 'Webster',
       'Allamakee', 'Buchanan', 'Bremer', 'Hancock', 'Kossuth', 'Sac',
       'Plymouth', 'Ida', 'Lucas', 'Davis', 'Benton', 'Clay', 'Mitchell',
       'Dubuque', 'Pottawattamie', 'Floyd', 'Hamilton', 'Sioux',
       'Marshall', 'Union', "O'Brien", 'Tama', 'Montgomery', 'Taylor',
       'Humboldt', 'Dickinson', 'Lyon', 'Jones', 'Wright', 'Cherokee',
       'Butler', 'Page', 'Emmet', 'Palo Alto', 'Adair', 'Mills',
       'Ringgold', 'Adams', 'Howard', 'Chickasaw', 'Hardin', 'Grundy',
       'Pocahontas', 'Osceola', 'Clayton', 'Jefferson', 'Muscatine',
       'Des Moines', 'Cass', 'Guthrie', 'Lee', 'Jackson', 'Washington',
       'Henry', 'Louisa', 'Delaware', 'Harrison', 'Franklin', 'Van Buren',
       'Keokuk', 'Shelby', 'Audubon', 'Wayne', 'Fremont'], dtype=object)

In [202]:
# 5 smallest counties: Adams, Ringgold, Audubon, Taylor, Wayne
# 5 largest counties: Polk, Linn, Scott, Black Hawk, Johnson

def size(county):
    if 'Polk' in county: 
        county = 'HighPop'
    elif 'Linn' in county:
        county = 'HighPop'
    elif 'Scott' in county: 
        county = 'HighPop'
    elif 'Black Hawk' in county: 
        county = 'HighPop'
    elif 'Johnson' in county:
        county = 'HighPop'
    elif 'Adams' in county: 
        county = 'LowPop'
    elif 'Ringgold' in county:
        county = 'LowPop'
    elif 'Audubon' in county:
        county = 'LowPop'
    elif 'Taylor' in county: 
        county = 'LowPop'
    elif 'Wayne' in county:
        county = "LowPop"
    else:
        pass

High_Pop = df.loc[(df['County Name'] == 'HighPop')]
Low_Pop = df.loc[(df['County Name'] == 'LowPop')]

NameError: name 'Polk' is not defined

Polk
Linn
Scott
Black Hawk
Johnson
Adams
Ringgold
Audubon
Taylor
Wayne
turkey